[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fantazia"
version = "0.0.1"
authors = [{ name = "F. X. P.", email = "vanleefxp@gmail.com" }]
description = "A package for math-based music theory computation."
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
]
keywords = ["music"]

[project.urls]
Homepage = "https://github.com/vanleefxp/fantazia"
Issues = "https://github.com/vanleefxp/fantazia/issues"
